### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by bording**
This PR requires a version of the ServiceControl.Monitoring.Data package built from https://github.com/Particular/ServiceControl.Monitoring.Data/pull/9, which brings in the code via source.

This means that ILRepack isn't needed, which doesn't really properly build a netstandard assembly in the first place.

I've also moved to using Particular.Packaging, and added `netcoreapp2.0` targets to the test projects.

### CODE REVIEW

**Comment by Scooletz** [comment]
@bording I do understand that with shipping sources ILRepack is not needed, but I see no reason for not-ILRepacking stated explicitly. Can you provide a link to an article, or to some of our findings?

@Particular/metrics-maintainers could you chime in please?

**Comment by tmasternak** [comment]
> which doesn't really properly build a netstandard assembly in the first place.

I would like to understand this as well.

**Comment by bording** [comment]
> I would like to understand this as well.

ILRepack doesn't currently support portable PDBs, which are what you want to use for .NET Standard assemblies since they can be used on non-Windows platforms.

Even if you do use full PDBs, the resulting assembly does not appear to be a valid .NET Standard assembly. It has a reference to mscorlib, and appears to be targeting .NET Framework 4.

**Comment by bording** [comment]
@Scooletz Why did you merge release-3.0 into this PR? It appears that it's brought in changes that shouldn't be here.

**Comment by Scooletz** [comment]
I'm working on it.

**Comment by Scooletz** [comment]
@bording ☝️

**Pull request merged**
