### PR TITLE
[WIP] Add instance key

### LINKED ISSUE #27: Restarting sender does not update the queue length metric on the receiver
Problem:

When all the endpoints are run the first time, the ServicePulse Monitoring dashboard reports queue length correctly. 

Restarting the sending and receiving endpoint, and running the same load test, the dashboard shows all of the other metrics, such as Processing time, Critical time, etc increasing, but queue length remains at 0. 

@mikeminutillo was able to repro this on the monitoring demo after updating to RC bits.

### PR DESCRIPTION
**Pull request by mikeminutillo**
Fixes #27 

The source for messages is now (EndpointName, Destination, InstanceKey). The InstanceKey is generated every time the endpoint starts. 

There will be a corresponding PR in the Monitoring server to track each instance independently under a link between (EndpointName, Destination) to the receiving endpoint.

### CODE REVIEW

**Comment by mikeminutillo** [comment]
The server can parse out the instance key and handle each instance separately as of https://github.com/Particular/ServiceControl.Monitoring/pull/113

**Comment by Scooletz** [comment]
Being given the fact that currently we're considering a support for native queue length measurement, should we treat it still as an active PR @mikeminutillo ?

**Comment by mikeminutillo** [comment]
@Scooletz hold off for now. We'll re-evaluate next week.

**Comment by tmasternak** [comment]
We are switching to native-queue length and the estimated version is not going to be fixed.

**Pull request closed without merging**
